server:
  port: 10086
spring:
  application:
    name: supermarket-registry

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    register-with-eureka: true   #禁止自己当做服务注册
    fetch-registry: true   #屏蔽注册信息
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
